# Generated by Django 5.2.6 on 2025-09-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_aboutme_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="A brief title for the resume, e.g., 'My Resume'", max_length=100)),
                ('file', models.FileField(upload_to='resume_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
